# Generated by Django 5.0.4 on 2024-05-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('trade_name', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('state_registration', models.CharField(max_length=20, verbose_name='Inscrição Estadual')),
                ('municipal_registration', models.CharField(max_length=20, verbose_name='Inscrição Municipal')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('website', models.URLField(max_length=100, verbose_name='Website')),
                ('opening_date', models.DateField(verbose_name='Data de Abertura')),
                ('main_activity', models.CharField(max_length=100, verbose_name='Atividade Principal')),
                ('secondary_activity', models.CharField(max_length=100, verbose_name='Atividade Secundária')),
                ('responsible_name', models.CharField(max_length=100, verbose_name='Nome do Responsável')),
                ('notes', models.TextField(verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
