# Generated by Django 5.0.4 on 2024-05-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name'], 'verbose_name': 'Dados da Empresa', 'verbose_name_plural': 'Dados das Empresas'},
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_entity/logos', verbose_name='Logo'),
        ),
    ]
