# Generated by Django 5.0.4 on 2024-05-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_entity', '0003_sitefooter_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='main_activity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atividade Principal'),
        ),
        migrations.AlterField(
            model_name='company',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='company',
            name='opening_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='company',
            name='secondary_activity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Atividade Secundária'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_registration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Website'),
        ),
    ]
