# Generated by Django 5.0.4 on 2024-05-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_entity', '0006_sitefooter_main_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefooter',
            name='name',
            field=models.CharField(default='Rodapé padrão do site', max_length=100, verbose_name='Nome do rodapé (controle interno)'),
        ),
    ]
