# Generated by Django 5.0.4 on 2024-05-08 14:08

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_entity', '0008_company_social_media_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefooter',
            name='service_hours',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=200, verbose_name='Horário de Atendimento'),
        ),
    ]
