# Generated by Django 5.0.4 on 2024-05-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_entity', '0011_alter_sitefooter_service_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefooter',
            name='main_footer',
            field=models.BooleanField(default=True, unique=True, verbose_name='Rodapé Principal'),
        ),
    ]
