# Generated by Django 5.0.4 on 2024-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_entity', '0013_alter_sitefooter_main_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefooter',
            name='main_footer',
            field=models.BooleanField(default=True, error_messages='Já existe um rodapé principal definido', help_text='Marque para definir como rodapé principal do site', verbose_name='Rodapé Principal'),
        ),
    ]
