# Generated by Django 5.0.4 on 2024-05-08 14:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_entity', '0014_alter_sitefooter_main_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefooter',
            name='main_footer',
            field=models.BooleanField(default=True, error_messages={'unique': 'Já existe um rodapé principal definido'}, help_text='Marque para definir como rodapé principal do site', unique=True, verbose_name='Rodapé Principal'),
        ),
        migrations.AlterField(
            model_name='sitefooter',
            name='service_hours',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Horário de Atendimento'),
        ),
    ]
