# Generated by Django 5.0.4 on 2024-05-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_entity', '0018_partner_company_is_active_alter_company_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('1', 'Pessoa Jurídica'), ('2', 'Pessoa Física')], default='1', max_length=1, verbose_name='Natureza do Parceiro'),
        ),
        migrations.AddField(
            model_name='partner',
            name='role',
            field=models.CharField(choices=[('1', 'Parceiro'), ('2', 'Fornecedor')], default='1', max_length=1, verbose_name='Tipo de Parceiro'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
