# Generated by Django 5.0.4 on 2024-04-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people/photos/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('role_type', models.CharField(choices=[('Diretoria', 'Diretoria'), ('Equipe', 'Equipe'), ('Voluntário', 'Voluntário'), ('Estágiário', 'Estágiário')], default='Voluntário', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
