# Generated by Django 5.0.4 on 2024-05-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_teamlist_remove_people_role_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
