# Generated by Django 5.0.4 on 2024-05-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_people_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='people_team', to='people.teamlist'),
        ),
    ]
