# Generated by Django 5.0.4 on 2024-05-10 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_people_role_alter_people_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people_jobRole', to='people.jobrole'),
        ),
        migrations.AlterField(
            model_name='people',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='people_team', to='people.teamlist'),
        ),
    ]
