# Generated by Django 5.0.4 on 2024-05-10 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_people_role_alter_people_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='board_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='board_position', to='people.boardposition', verbose_name='Posição na Diretoria'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='people',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='people',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people_jobRole', to='people.jobrole', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='people',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='people_team', to='people.teamlist', verbose_name='Equipe'),
        ),
    ]
