# Generated by Django 5.0.4 on 2024-05-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='header_banners/', verbose_name='Header Banner Image')),
                ('title', models.CharField(max_length=40, verbose_name='Título')),
                ('description', models.CharField(max_length=140, verbose_name='Descrição')),
                ('call_to_action_button_text', models.CharField(max_length=40, verbose_name='Texto do botão de chamada à ação')),
                ('button_link', models.URLField(verbose_name='link')),
            ],
            options={
                'verbose_name': 'Banner do cabeçalho',
                'verbose_name_plural': 'Banners do cabeçalho',
            },
        ),
    ]
